---
name: P-Value Histogram
description: Plot an adjusted P-Value Histogram
authors:
  - Thibault Dayris
input:
  - A TSV-formatted deseq2 result
output:
  - A PNG-formatted image of the pvalue repartition
notes: |
  Parameters:

  
