rule test_snpsift_dbnsfp:
    input:
        vcf = "in.vcf",
        dbNSFP = "dbNSFP.txt.gz"
    output:
        vcf = "annotated/out.vcf"
    message:
        "Testing SnpSift dbNSFP annotation"
    log:
        "annotate.log"
    wrapper:
        "master/bio/snpsift/dbnsfp"
