---
name: SnpSift dnNSFP
description:  Annotate using integrated annotation from dbNSFP.
authors:
  - Thibault Dayris
input:
  - A VCF-formatted file that is to be annoated
  - A dnNSFP text file
output:
  - A VCF-formatted file
note: |
  The dbNSFP is an integrated database of functional predictions from multiple
  algorithms (SIFT, Polyphen2, LRT and MutationTaster, PhyloP and GERP++, etc.)

  Use the -f argument to select columns in your dbnsfp file 
