---
name: nbinomWaldTest
description: Wald test for the GLM coefficients
authors:
  - Thibault Dayris
input:
  - A DESeq2 Dataset with effect size estimates, and dispersion estimates.
output:
  - A RDS object containing the DESeq2 Dataset with binomial Wald Test result
  - A TSV-formated text file for each level included in the DESeq2 Dataset
notes: |
  Parameters:

  * alpha_threshold: The padj threshold used to filter the result table
  * fc_threshold: The fold change threshold used to filter the result table
