---
name: DESeq2 to GSEAapp
description: Creates the GSEA files from DESeq2 output
authors:
  - Thibault Dayris
input:
  - A TSV formatted text file containing the DESeq2 wald tests results
output:
  - A TSV with Gene / FoldChange / Up-Down cluster
  - A TSV with Gene / FoldChange / Significance cluster
  - A TSV with Gene / Adjusted Pvalue / Up-Down cluster
  - A TSV with Gene / Adjusted Pvalue / Significance cluster
  - A complete table with all of the above
notes: |
  THe first column is set a column index

  Parameters:

  * alpha: The alpha threshold (float)
  * fold_change: The fold change threshold (float)
  * general_table_only: Weather to output only the complete table described above (bool)
