---
name: SnpSift GWAS Catalog
description:  Annotate using GWAS catalog.
authors:
  - Thibault Dayris
input:
  - A VCF-formatted file that is to be annoated
  - A GWAS Catalog TSV-formatted file
output:
  - A VCF-formatted file
note: |
  To find gwas catalog: https://www.ebi.ac.uk/gwas/docs/file-downloads
