---
name: SnpSift Genes Sets
description:  Annotate using GMT genes sets.
authors:
  - Thibault Dayris
input:
  - A VCF-formatted file that is to be annoated
  - A GMT-formatted text file
output:
  - A VCF-formatted file
note: |
  You may look for GMT files here: https://www.gsea-msigdb.org/gsea/msigdb
