---
name: Pandas Merge
authors:
  - Thibault Dayris
input:
  - A list of paths to salmon quannt.sf or quant.genes.sf
output:
  - A TSV-formatted text file with all TPM or RawCounts
notes: |
  As a parameter within "col", any column of the Salmon quant file shall be set.
