---
name: Pandas Merge
description: Merge salmon quant.sf files
authors:
  - Thibault Dayris
input:
  - A list of paths to salmon quannt.sf or quant.genes.sf
output:
  - A TSV-formatted text file with all TPM or RawCounts
notes: |
  Parameters:

  * suffix: Suffix that is to be removed from sample identifier
  * prefix: Prefix that is to be removed from sample identifier
  * column: The column to keep in the merged table
  * gencode: Remove patch from sample identifiers
  * drop_na: Drop full NA targets
  * drop_null: Drop full null targets
  * genes: Work on genes and not on transcripts
  * header: There is a header in the tx2gene table
  * index_label: The index label in the tx2gene
