name: DESeqDataSetFromTximport
author: Thibault Dayris
description: Import counts from Tximport into DESeq2
input:
  - A tximport RDS file
  - A TSV design file as described in DESeq2 documentation
output:
  - A RDS file of the DDS object.
notes: |
  Depending on your formula, your design file can contain any number of
  optional columns
