---
name: Seaborn Box plots
description: Build a count box-plot
authors:
  - Thibault Dayris
input:
  - A TSV-formatted normalized counts table of all samples
output:
  - A PNG-formatted image of the clustered heatmap
notes: |
  Parameters:

  * drop_null: Remove lines full of zeros or NaNs
