---
name: Add Genes
authors:
  - Thibault Dayris
description: Add a gene/transcript column to a given tsv
input:
  - A TSV-formatted text file with a gene/transcript id/name.
output:
  - A TSV-formatted text file with complete identifier and name for each gene.
notes: |
  Parameters:

  * header: There is a header in the tx2gene table
  * genes: Work on genes rather than transcripts
