---
name: pcaExplorer PCAScree
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bioconda:bioconductor-deseq2=1.26.0
  - bioconda:bioconductor-pcaexplorer=2.12.0
  - bioconda:bioconductor-delayedarray=0.12.0
  - conda-forge:r-readr=1.3.1
  - conda-forge:r-jsonlite=1.6.1
  - bioconda:bioconductor-summarizedexperiment=1.16.0
  - bioconda:bioconductor-iranges=2.20.0
  - conda-forge:cairo=1.16.0
  - conda-forge:r-cairo=1.5_11
