---
name: pcaExplorer PCA Correlation
description: Plot PCA axes correlations
authors:
  - Thibault Dayris
input:
  - A normalized dds (vst/rlog) of all samples and targets
  - A DESeq2 dataset
output:
  - A png image of the correlation of the requested axe with factors
note: |
  Parameters:

  * extra (str) Command line arguments (interpreted by R)
