---
name: PCA
description: Perform PCA on normalized counts
authors:
  - Thibault Dayris
input:
  - A TSV-formatted normalized counts table of all samples
output:
  - A PNG-formatted image of two selected axes of the PCA
notes: |
  Parameters:

  * conditions: List of conditions to color the PCA points
  * prefix: The output file prefix (_PCXX_PCYY.png will be added)
  * legend_position: The position of the legend and title
  * axes: the axis to plot
