---
name: Seaborn Clustermap
description: Build a clustered heatmap
authors:
  - Thibault Dayris
input:
  - A TSV-formatted normalized counts table of all samples
output:
  - A PNG-formatted image of the clustered heatmap
notes: |
  Parameters:

  * row_cluster: Perform clustering on rows
  * col_cluster: Perform clustering on columns
  * row_condition_color: Set colors on rows according to condition array
  * col_condition_color: Set colors on columns according to  condition array
  * square: Plot half of the heatmap
  * robust: Use robust quantiles instead of the extreme values
  * ylabel_rotation: The X label rotation
  * xlabel_rotation: The Y label rotation
