---
name: Pariwise scatterplot
description: Perform pairwise scatterplot on sample counts
authors:
  - Thibault Dayris
input:
  - A TSV-formatted normalized counts table of all samples
output:
  - A PNG-formatted pairwise scatterplot
