name: "trimmomatic pe"
description: Trim paired-end reads with trimmomatic. (De)compress with pigz.
authors:
  - Johannes Köster
  - Jorge Langa
note: |
  If you let fastq.gz files as input, this wrapper uses inner sub-shell
  invocation. Make sure you use at least two trheads in your Snakefile in
  that case.
