---
name: Filter design
description: Filter a design file
authors:
  - Thibault Dayris
input:
  - A TSV formatted text file containing a design
output:
  - A TSV formatted text file containing a subset of the provided design
notes: |
  There should be a column named "Sample_id". This will be the index of the
  dataframe.

  Parameters:

  * keep_sample: A lit of samples to keep. Others will be filtered out
  * filter_sample: A list of samples to filter out. Others will be kept
  * keep_column: A list fo columns to keep. Others will be filtered out
  * filter_column: A list of columns to filter out. Others will be kept
