---
name: pcaExplorer PCA
description: Plot PCA from a vst/rld transformed dds object
authors:
  - Thibault Dayris
input:
  - A normalized dds (vst/rlog) of all samples and targets
output:
  - A png image of the PCA and requested axes
note: |
  Parameters:

  * extra (str) Command line arguments (interpreted by R)
