---
name: Volcano-DESeq2
description: Plot a Volcano plot from DESeq2 raw results
authors:
  - Thibault Dayris
input:
  - A TSV-formatted DESeq2 table
output:
  - A PNG-formatted volcano plot
notes: |
  Parameters:

  * alpha_threshold: Significance threshold
  * fc_threshold: Fold change significance threshold
