---
name: pcaExplorer pair_corr
description: Plot the sample pairwise correlation
authors:
  - Thibault Dayris
input:
  - A normalized dds (vst/rlog) of all samples and targets
output:
  - A png image of the sample pairwise correlation
note: |
  Parameters:

  * extra (str) Command line arguments (interpreted by R)
