---
name: Clustermap
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - conda-forge:python=3.8.2
  - conda-forge:pandas=1.0.1
  - conda-forge:numpy=1.18.1
  - conda-forge:seaborn=0.10.0
  - conda-forge:matplotlib=3.1.3
  - conda-forge:pillow=7.0.0
