---
name: Seaborn Gene Box plots
description: Build a gene box-plot
authors:
  - Thibault Dayris
input:
  - A TSV-formatted normalized counts table of all samples
output:
  - A PNG-formatted image of the clustered heatmap
notes: |
  Parameters:

  * condition: a dictionnary containing each sample name and their corresponding condition
  * target: a list of genes/transcripts/targets to plot
