---
name: DESeqDataSetFromTximport
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bioconductor-tximport==1.14.0
  - r-readr==1.3.1
  - r-jsonlite==1.6
  - bioconductor-deseq2==1.26.0
