name: estimateDispersions
author: 
  - Thibault Dayris
description: Estimate the dispersions for a DESeqDataSet
input:
  - A deseq2 dataset as RDS
output:
  - A RDS file of the DDS object with dispertion estimates
notes: |
  Besides the RDS object, you can add any arguments in extra, they
  shall be interpreted within the "..." argument in R.
