---
name: tx_to_gene
description: Build a transcript / gene correspondancy table from a GTF
authors:
  - Thibault Dayris
input:
  - A path to a GTF file
output:
  - A TSV-formatted text file containing all transcript with their gene name
notes: |
  You can also request transcript start/end positions alongside with chromosome
  identifier.
  Headers in columns are optionals
