---
name: VST
author:
  - Thibault Dayris
description: Apply a variance stabilizing transformation
input:
  - A DESeq2 dataset as a RDS file
output:
  - A RDS file of the DDS object with VST transform
  - A TSV-formatted text file contianing the normalized count table
